changelog:
  exclude:
    labels:
      - ignore for release
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Improvements 🚀
      labels:
        - improvement
    - title: Documentation 📚
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"